### PR TITLE
Collegiate subreddits Get(Index) and Post(Create)

### LINKED ISSUE #13: Create `CollegiateSubredditController`, add `GET` (index) and `POST` (create)
Create `CollegiateSubredditController`, add `GET` (index) and `POST` (create)

# Acceptance Criteria:

- [x] There is a controller file `CollegiateSubredditController.java`
      in the expected directory.
- [x] In `CollegiateSubredditController.java` there is 
      code for a `GET /api/collegiateSubreddits/all` endpoint 
      that returns a JSON list of all subreddits in the database.
      (We sometimes call this an *index* action since it lists all
      items in the database.)
- [x] In `CollegiateSubredditController.java` there is 
      code for a `POST /api/collegiateSubreddits/post` endpoint
      that can be used to create a new entry in the table. (This
      is a *create* action.)
- [x] The Swagger-UI endpoints for these are well documented so that
      any member of the team can understand what they are for and
      how to use them.
- [x] The `POST` endpoint works as expected, in the sense that new
      records can be added to the database (on localhost).
- [x] The `GET` endpoint works as expected, in the sense that the new
      records that are added show up (on localhost).
- [x] The `GET` and `POST` endpoints work as expected when the 
      app is deployed to Heroku.
- [x] There is full test coverage (Jacoco) for the methods in 
      `CollegiateSubredditController.java`
- [x] There is full mutation test coverage (Pitest) for the methods in
      `CollegiateSubredditController.java`

# Details

Consult the methods in [`TodosController.java`](https://github.com/ucsb-cs156-w22/demo-spring-react-example-v2/blob/main/src/main/java/edu/ucsb/cs156/example/controllers/TodosController.java) for examples 
of controller methods.

Consult the tests in [`TodosControllerTests.java`](https://github.com/ucsb-cs156-w22/demo-spring-react-example-v2/blob/main/src/test/java/edu/ucsb/cs156/example/controllers/TodosControllerTests.java) for examples
of controller tests.

### PR DESCRIPTION
**Pull request by qianyouwang**
In this PR, two endpoints api/collegiateSubreddits/all and /api/collegiateSubreddits/post are created and worked well on localhost. The first one returns all the record subreddit infos and the latter one can create a new subreddit and store it in the database. This is related to issue #13.

Maven Test
Screen Shot 2022-02-07 at 15 36 41

Jacoco Report
Screen Shot 2022-02-07 at 15 37 06

Mutation Test
Screen Shot 2022-02-07 at 15 37 17

### CODE REVIEW

**Comment by SwiftWinds** [comment]
@qianyouwang please don't assign everyone; just 1-2 ppl is enough. I'll assign just @tekaireb for this if he's ok with that

**Comment by nguglielmin** [comment]
> @qianyouwang please don't assign everyone; just 1-2 ppl is enough. I'll assign just @tekaireb for this if he's ok with that

@tekaireb is already assigned to [our PR](https://github.com/ucsb-cs156-w22/team02-w22-5pm-3/pull/32) (just need one of him or Isaiah to review) so I can take this one!

**Review by nguglielmin — COMMENTED** [review]
I'm curious why you commented out the `@PreAuthorize` lines. Otherwise looks good!

**Comment by qianyouwang** [comment]
> I'm curious why you commented out the `@PreAuthorize` lines. Otherwise looks good!

I commented this out just because it seems like we did not have any function to distinguish users and admin up til now so I guess its redundant? I am just looking at the rubric basically to determine my code. :)

**Pull request merged**
